---
layout: cv
title: Naoto Nakatani's CV
---
# Naoto Nakatani

<div id="webaddress">
<a href="nak24019@byui.edu">nak24019@byui.edu</a>
| <a href="http://www.linkedin.com/in/naoto-nakatani">IinkedIn</a>
</div>


## Academic Projects

`Spring 2025`
__Disease Spread Simulation (Python Project)__
- Developed an interactive disease spread simulator using Python and Tkinter.
- Implemented probabilistic infection, recovery, and mortality models.
- Applied OOP principles to manage simulation states and graphical rendering.
- Tracked and visualized metrics such as steps, peak infection, and recoveries.


## Education


`Apr 2025 - now`    
__Brigham Young University - Idaho, Idaho__


## Experience


`Apr 2024 – Nov 2024`
__Mikuni International College – Computer Science Teaching Assistant__
- Assisted in teaching CS classes and grading assignments and exams.
- Provided one-on-one student support to improve coursework understanding.
- Collaborated with instructors to enhance teaching quality.
- Served as a student leader coordinating meetings with faculty and volunteers.


`Mar 2022 – Apr 2024`
__Community Volunteer Representative — Fukuoka, Japan__
- Dedicated 70+ hours/week to community outreach and service projects.
- Trained and mentored 10+ team members in communication and leadership.
- Organized weekly meetings and coordinated with local organizations.



- **Computer Skills:** MS Word, Excel, PowerPoint, Python  
- **Languages:** Fluent in Japanese; basic Chinese  
- **Work Eligibility:** Eligible to work in the U.S.; will require visa sponsorship for full-time employment